name: Generate Snake Animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake 🐍
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Jpontess
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar animação na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

